BEGIN TRANSACTION;
DROP VIEW vPersonne;
DROP VIEW vLimite;
DROP VIEW vIllimite;
DROP TABLE Manager CASCADE;
DROP TABLE Intervenant CASCADE;
DROP TABLE Coworker CASCADE;
DROP TABLE Espace CASCADE;
DROP TABLE Conference CASCADE;
DROP TABLE Domaines_activite CASCADE;
DROP TABLE Assoc_CoworkerDomaine CASCADE;
DROP TABLE Elements_descripteurs CASCADE;
DROP TABLE Description CASCADE;
DROP TABLE Salles_Collectives CASCADE;
DROP TABLE Actualites CASCADE;
DROP TABLE Formule CASCADE;
DROP TABLE Assoc_Propose CASCADE;
DROP TABLE Assoc_CoworkerFormule CASCADE;
DROP TABLE Assoc_Espace_Ouvert_Conference CASCADE;

COMMIT TRANSACTION;
